import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'

import Form from '~/components/Form'
import Header from '~/components/Header'
import FormProvider from '~/providers/FormProvider'

const Home: NextPage = () => {
  return (
    <div className="wrapper">
      <Head>
        <title>Conditional Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center">
        <FormProvider>
          <Header />

          <Form />
        </FormProvider>
      </main>
    </div>
  )
}

export default Home
